# -*- coding: utf-8 -*-
"""reklama_sales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHkq_chs0ksb8a3CiJ8D_-3pSdwwwkNK
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn 
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("/content/reklama_sales.csv")
df.head()

"""Yuqoridagi jadvalda MohirDev MChJ tomonidan turli OAV larda (TV, Radio, Newspaper) berilgan reklamalar soni va mos keluvchi savdolar (Sales) berilgan.

Sizning vazifangiz:

*  Aynan qaysi turdagi OAVda reklama berish savdo o'sishiga ta'sir qiladi aniqlash
*  Topilgan bog'liqlik asosida Simple Linear Regression algorithmi yordamida bashorat modelini qurish.
*  Ushbu amaliyotda sizning vazifangiz berilgan dataset yordamida Simple Linear Regression model yaratish:

*   CRISP-DM metodologiyasiga amal qiling!
*   Simple linear regression qo'llash uchun 1 ta ustunni tanlab oling.
"""

# ma'lumotlarni o'rganamiz
df.info()

df.describe()

df.isnull().sum()

df.corrwith(df["Sales"]).sort_values(ascending=False)  # ajoyib correlatsiya TV bilan ekan,1-shartga javob topdik!!!

sns.heatmap(data=df.corr(),annot=True,cmap="BuPu_r")
plt.show()

sns.scatterplot(data=df,x='TV',y="Sales")
plt.show()

sns.regplot(data=df,x="TV",y="Sales",line_kws={"color":"red"})
plt.show()    #biz aynan algoritm yordamida mana shu qizil chiziq formula koeffitsiyentlarini keltirishimiz kerak

"""**Algoritmni quramiz......**

y = theta0 + theta1*x   - qiymatlar shu formula orqali aniqlanadi


```
1) theta0 va theta1 koeffitsient
2) x qiymat
```
"""

X = df["TV"].to_numpy()
Y = df["Sales"].to_numpy()

df[["TV"]].to_numpy().shape

Xmean=np.mean(X)
Ymean=np.mean(Y)

theta1=sum((X-X_mean)*(Y-Ymean))/sum((X-Xmean)**2)
theta0=Ymean-theta1*Xmean

plt.figure(figsize=(10,8))
sns.scatterplot(data=df,x=X,y=Y)
plt.plot(X,theta0+theta1*X,c="r")

print(f"theta0 = {theta0}")
print(f"theta1 = {theta1}")

from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(df,random_state=21,train_size=0.8)

#theta0 va theta1 koeffitsiyentlarni boshqa usulda ham topish mumkin
from sklearn.linear_model import LinearRegression
LR_model = LinearRegression()

X_train=np.asanyarray(train_set[["TV"]])
Y_train=np.asanyarray(train_set[["Sales"]])

LR_model.fit(X_train,Y_train)

from matplotlib.projections.polar import ThetaTick
thetaa1=LR_model.coef_[0][0]
thetaa0=LR_model.intercept_[0]
print(f'theta1={thetaa1}')
print(f'theta0={thetaa0}')

theta0

theta1

"""**Modelni baholaymiz**

"""

X_test = np.asanyarray(test_set[["TV"]])
X_test = np.asanyarray(test_set[["Sales"]])
predict_test = LR_model.predict(X_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error
MAE = mean_absolute_error(predict_test,X_test)
RMSE = np.sqrt(mean_squared_error(predict_test,X_test))
print(f"MAE={MAE}")
print(f"RMSE={RMSE}")

